require("./template/ajax-form")
require ("./template/bootstrap.min")
require("./template/contact")
require("./template/gijgo.min")
require("./template/imagesloaded.pkgd.min")
require("./template/isotope.pkgd.min")
require("./template/jquery.ajaxchimp.min")
require("./template/jquery.counterup.min")
require("./template/jquery.form")
require("./template/jquery.magnific-popup.min")
require("./template/jquery.scrollUp.min")
require("./template/jquery.slicknav.min")
require("./template/jquery.validate.min")
require("./template/mail-script")
require("./template/main")
require("./template/nice-select.min")
require("./template/owl.carousel.min")
require("./template/plugins")
require("./template/popper.min")
require("./template/scrollIt")
require("./template/waypoints.min")
require("./template/wow.min")

require("./template/vendor/jquery-1.12.4.min")
require("./template/vendor/modernizr-3.5.0.min")